version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # <— set this
      MYSQL_DATABASE: motopp
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 10

  motopp:
    build: ./motopp
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_HOST: mysql
      MYSQL_USER: root                 # <— no MYSQL_PASSWORD here
      MYSQL_DATABASE: motopp
      FLASK_ENV: production
    ports:
      - "5000:5000"
    command: ["sh", "-c", "sleep 10 && /app/motopp/run.sh -d 0"]

volumes:
  mysql_data: {}
